name: build-web
description: Build Tonkeeper Web Wallet
inputs:
    environment:
    node_version:
        required: true
            outputs:
outputs:
    deployment-url:
runs:
    using: composite
    steps:
        - name: Checkout to git repository
          uses: actions/checkout@v4

        - name: Set up Node
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node_version }}

        - name: Enable Corepack
          run: |
              corepack enable

        - name: Run install
          uses: borales/actions-yarn@v5
          with:
              cmd: install

        - name: Run build
          uses: borales/actions-yarn@v5
          env:
              VITE_APP_AMPLITUDE: ${{ secrets.REACT_APP_AMPLITUDE_EXTENSION }}
              VITE_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
              VITE_APP_APTABASE: ${{ secrets.VITE_APP_APTABASE }}
              VITE_APP_APTABASE_HOST: https://anonymous-analytics.tonkeeper.com
              VITE_APP_LOCALES: en,zh_TW,zh_CN,id,ru,it,es,uk,tr,bg,uz,bn
              VITE_APP_TONCONSOLE_HOST: https://pro.tonconsole.com
              VITE_APP_TG_BOT_ID: ${{ secrets.REACT_APP_TG_BOT_ID }}
              VITE_APP_STONFI_REFERRAL_ADDRESS: ${{ secrets.REACT_APP_STONFI_REFERRAL_ADDRESS }}
          with:
              cmd: build:web

        - name: Publish to Cloudflare Pages
          id: deploy
          uses: cloudflare/wrangler-action@v3
          with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              command:
                  pages deploy apps/web/dist --project-name=tonkeeper-web --branch=${{
                  inputs.environment }}

        - id: Pass deployment-url output
          run: echo "deployment-url=${{ steps.deploy.outputs.deployment-url }}" >> "$GITHUB_OUTPUT"

        - name: Summary
          run: |
              echo '### Successful WEB deployment 🚀🚀🚀' >> $GITHUB_STEP_SUMMARY
              echo 'Well done!' >> $GITHUB_STEP_SUMMARY
              echo 'Link to test environment:' >> $GITHUB_STEP_SUMMARY
              echo '${{ steps.deploy.outputs.deployment-url }}' >> $GITHUB_STEP_SUMMARY

        - name: Comment PR
          uses: thollander/actions-comment-pull-request@v3
          if: github.event_name == 'pull_request'
          with:
              message: |
                  ### Successful WEB deployment 🚀🚀🚀
                  Well done!
                  Link to test environment:
                  ${{ steps.deploy.outputs.deployment-url }}
              comment-tag: web_deploy
